"""Compare DOCX rendering approaches from Python.

This is a standalone mockup/prototype. Heavy and machine-specific libraries are
probed at runtime so the production app does not inherit these dependencies.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime
import html
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import textwrap
import time
import traceback
from typing import Callable, Iterable


ROOT = Path(__file__).resolve().parent
DEFAULT_OUTPUT_ROOT = ROOT / "_outputs"
QUICK_RENDERERS = ("python_docx_html_qt", "mammoth_html_qt", "pypandoc_html_qt")

HTML_CSS = """
@page { size: Letter; margin: 0.72in; }
* { box-sizing: border-box; }
body {
  color: #1f2933;
  font-family: "Segoe UI", Arial, sans-serif;
  font-size: 10.5pt;
  line-height: 1.48;
}
h1 { color: #17324d; font-size: 23pt; margin: 0 0 8pt; }
h2 { color: #24557a; font-size: 16pt; margin: 18pt 0 6pt; }
h3 { color: #24557a; font-size: 12pt; margin: 12pt 0 5pt; }
p { margin: 0 0 8pt; }
table { border-collapse: collapse; margin: 10pt 0 14pt; width: 100%; }
th, td { border: 1px solid #a7b3c0; padding: 6pt 7pt; vertical-align: top; }
th { background: #e9f0f7; color: #17324d; font-weight: 700; }
.doc-meta { color: #52616f; font-size: 9pt; margin-bottom: 14pt; }
.callout { background: #eef6f0; border-left: 5px solid #2f8f5b; padding: 9pt 11pt; }
.muted { color: #65717c; }
.extracted { background: #f6f8fa; border: 1px solid #d0d7de; padding: 10pt; white-space: pre-wrap; }
img { max-width: 100%; }
"""


class SkipRenderer(RuntimeError):
    """Raised when a renderer is intentionally unavailable on this machine."""


@dataclass(frozen=True)
class Renderer:
    name: str
    label: str
    kind: str
    description: str
    func: Callable[[Path, Path, int], dict[str, object]]


def _rel(path: Path, base: Path) -> str:
    try:
        return path.resolve().relative_to(base.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _json_safe_result(
    *,
    name: str,
    label: str,
    kind: str,
    status: str,
    note: str,
    duration_s: float,
    output_dir: Path,
    artifacts: dict[str, Path] | None = None,
    pages: list[Path] | None = None,
    details: str = "",
) -> dict[str, object]:
    artifacts = artifacts or {}
    pages = pages or []
    return {
        "name": name,
        "label": label,
        "kind": kind,
        "status": status,
        "note": note,
        "duration_s": round(duration_s, 3),
        "artifacts": {key: _rel(value, output_dir) for key, value in artifacts.items()},
        "pages": [_rel(page, output_dir) for page in pages],
        "details": details,
    }


def _check_file(path: Path, label: str) -> None:
    if not path.exists() or path.stat().st_size <= 0:
        raise RuntimeError(f"{label} was not created: {path}")


def _rasterize_pdf(pdf_path: Path, output_dir: Path, *, max_pages: int) -> list[Path]:
    import fitz

    pages_dir = output_dir / "pages"
    pages_dir.mkdir(parents=True, exist_ok=True)
    rendered: list[Path] = []
    with fitz.open(str(pdf_path)) as document:
        page_count = min(len(document), max_pages)
        for index in range(page_count):
            page = document.load_page(index)
            pixmap = page.get_pixmap(matrix=fitz.Matrix(2.0, 2.0), alpha=False)
            page_path = pages_dir / f"page_{index + 1:03d}.png"
            pixmap.save(str(page_path))
            rendered.append(page_path)
    if not rendered:
        raise RuntimeError(f"No pages were rasterized from {pdf_path}")
    return rendered


def _html_document(title: str, body: str) -> str:
    return textwrap.dedent(
        f"""\
        <!doctype html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>{html.escape(title)}</title>
          <style>{HTML_CSS}</style>
        </head>
        <body>
          <h1>{html.escape(title)}</h1>
          <p class="doc-meta">Generated by the DOCX rendering comparison prototype.</p>
          {body}
        </body>
        </html>
        """
    )


def _inject_css_if_full_html(source: str) -> str:
    style = f"<style>{HTML_CSS}</style>"
    lower = source.lower()
    if "</head>" in lower:
        index = lower.rfind("</head>")
        return source[:index] + style + source[index:]
    if "<html" in lower:
        return source
    return _html_document("Pandoc HTML conversion", source)


def _write_html_then_pdf(
    *,
    html_text: str,
    html_path: Path,
    pdf_path: Path,
    output_dir: Path,
    max_pages: int,
) -> tuple[dict[str, Path], list[Path]]:
    html_path.write_text(html_text, encoding="utf-8")
    _html_file_to_pdf_qt(html_path, pdf_path)
    _check_file(pdf_path, "PDF")
    pages = _rasterize_pdf(pdf_path, output_dir, max_pages=max_pages)
    return {"html": html_path, "pdf": pdf_path}, pages


def _html_file_to_pdf_qt(html_path: Path, pdf_path: Path) -> None:
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    os.environ.setdefault("QTWEBENGINE_CHROMIUM_FLAGS", "--disable-gpu --no-sandbox")

    from PyQt6.QtCore import QEventLoop, QTimer, QUrl
    from PyQt6.QtWebEngineCore import QWebEnginePage
    from PyQt6.QtWidgets import QApplication

    app = QApplication.instance() or QApplication(sys.argv[:1])
    page = QWebEnginePage()

    load_state = {"done": False, "ok": False}
    load_loop = QEventLoop()

    def on_load_finished(ok: bool) -> None:
        load_state["done"] = True
        load_state["ok"] = ok
        load_loop.quit()

    page.loadFinished.connect(on_load_finished)
    page.load(QUrl.fromLocalFile(str(html_path.resolve())))
    QTimer.singleShot(30000, load_loop.quit)
    load_loop.exec()
    if not load_state["done"]:
        raise TimeoutError(f"Timed out loading HTML in Qt WebEngine: {html_path}")
    if not load_state["ok"]:
        raise RuntimeError(f"Qt WebEngine failed to load HTML: {html_path}")

    print_state = {"done": False, "ok": False}
    print_loop = QEventLoop()

    def on_pdf_finished(_path: str, ok: bool) -> None:
        print_state["done"] = True
        print_state["ok"] = ok
        print_loop.quit()

    page.pdfPrintingFinished.connect(on_pdf_finished)
    page.printToPdf(str(pdf_path.resolve()))
    QTimer.singleShot(30000, print_loop.quit)
    print_loop.exec()
    page.deleteLater()
    app.processEvents()
    if not print_state["done"]:
        raise TimeoutError(f"Timed out printing HTML to PDF: {html_path}")
    if not print_state["ok"]:
        raise RuntimeError(f"Qt WebEngine failed to print PDF: {pdf_path}")


def _pdf_result(pdf_path: Path, output_dir: Path, max_pages: int) -> tuple[dict[str, Path], list[Path]]:
    _check_file(pdf_path, "PDF")
    pages = _rasterize_pdf(pdf_path, output_dir, max_pages=max_pages)
    return {"pdf": pdf_path}, pages


def _find_libreoffice_executable() -> str | None:
    configured = os.environ.get("LIBREOFFICE_SOFFICE_PATH")
    candidates = [
        Path(configured) if configured else None,
        Path(os.environ.get("LOCALAPPDATA", "")) / "LibreOfficeAdminImage" / "program" / "soffice.exe",
        Path(os.environ.get("ProgramFiles", "")) / "LibreOffice" / "program" / "soffice.exe",
        Path(os.environ.get("ProgramFiles(x86)", "")) / "LibreOffice" / "program" / "soffice.exe",
    ]
    for candidate in candidates:
        if candidate and candidate.exists():
            return str(candidate)
    return shutil.which("soffice") or shutil.which("libreoffice")


def _render_word_com_pdf(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    import win32com.client

    pdf_path = output_dir / "word_com.pdf"
    word = None
    document = None
    try:
        word = win32com.client.DispatchEx("Word.Application")
        word.Visible = False
        word.DisplayAlerts = 0
        document = word.Documents.Open(str(input_docx.resolve()), ReadOnly=True)
        document.ExportAsFixedFormat(str(pdf_path.resolve()), 17)
    finally:
        if document is not None:
            document.Close(False)
        if word is not None:
            word.Quit()
    artifacts, pages = _pdf_result(pdf_path, output_dir, max_pages)
    return {"note": "Rendered through Microsoft Word COM automation.", "artifacts": artifacts, "pages": pages}


def _render_docx2pdf_word(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    from docx2pdf import convert

    pdf_path = output_dir / "docx2pdf_word.pdf"
    convert(str(input_docx.resolve()), str(pdf_path.resolve()))
    artifacts, pages = _pdf_result(pdf_path, output_dir, max_pages)
    return {"note": "Rendered through docx2pdf, which delegates to Microsoft Word on Windows.", "artifacts": artifacts, "pages": pages}


def _render_aspose_words_pdf(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    import aspose.words as aw

    pdf_path = output_dir / "aspose_words.pdf"
    document = aw.Document(str(input_docx.resolve()))
    document.save(str(pdf_path.resolve()), aw.SaveFormat.PDF)
    artifacts, pages = _pdf_result(pdf_path, output_dir, max_pages)
    return {"note": "Rendered through Aspose.Words. Evaluation watermarks may appear without a license.", "artifacts": artifacts, "pages": pages}


def _render_spire_doc_pdf(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    from spire.doc import Document, FileFormat

    pdf_path = output_dir / "spire_doc.pdf"
    document = Document()
    try:
        document.LoadFromFile(str(input_docx.resolve()))
        document.SaveToFile(str(pdf_path.resolve()), FileFormat.PDF)
    finally:
        document.Close()
    artifacts, pages = _pdf_result(pdf_path, output_dir, max_pages)
    return {"note": "Rendered through Spire.Doc. Evaluation marks may appear without a license.", "artifacts": artifacts, "pages": pages}


def _render_libreoffice_pdf(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    executable = _find_libreoffice_executable()
    if not executable:
        raise SkipRenderer("LibreOffice executable was not found on PATH.")
    result = subprocess.run(
        [
            executable,
            "--headless",
            "--convert-to",
            "pdf",
            "--outdir",
            str(output_dir.resolve()),
            str(input_docx.resolve()),
        ],
        text=True,
        capture_output=True,
        timeout=120,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "LibreOffice conversion failed.")
    produced = output_dir / f"{input_docx.stem}.pdf"
    pdf_path = output_dir / "libreoffice.pdf"
    if produced.exists() and produced != pdf_path:
        produced.replace(pdf_path)
    artifacts, pages = _pdf_result(pdf_path, output_dir, max_pages)
    return {"note": "Rendered through LibreOffice headless CLI.", "artifacts": artifacts, "pages": pages}


def _render_pypandoc_html_qt(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    import pypandoc

    raw_html = output_dir / "pandoc_raw.html"
    media_dir = output_dir / "media"
    media_dir.mkdir(exist_ok=True)
    pypandoc.convert_file(
        str(input_docx.resolve()),
        "html",
        outputfile=str(raw_html.resolve()),
        extra_args=["--standalone", f"--extract-media={media_dir.resolve()}"],
    )
    html_text = _inject_css_if_full_html(raw_html.read_text(encoding="utf-8"))
    html_path = output_dir / "pypandoc.html"
    pdf_path = output_dir / "pypandoc_qt.pdf"
    artifacts, pages = _write_html_then_pdf(
        html_text=html_text,
        html_path=html_path,
        pdf_path=pdf_path,
        output_dir=output_dir,
        max_pages=max_pages,
    )
    artifacts["raw_html"] = raw_html
    return {"note": "Converted with Pandoc, then printed with Qt WebEngine.", "artifacts": artifacts, "pages": pages}


def _render_mammoth_html_qt(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    import mammoth

    with input_docx.open("rb") as handle:
        result = mammoth.convert_to_html(handle)
    messages = "; ".join(str(message) for message in result.messages)
    html_text = _html_document("Mammoth HTML conversion", result.value)
    html_path = output_dir / "mammoth.html"
    pdf_path = output_dir / "mammoth_qt.pdf"
    artifacts, pages = _write_html_then_pdf(
        html_text=html_text,
        html_path=html_path,
        pdf_path=pdf_path,
        output_dir=output_dir,
        max_pages=max_pages,
    )
    note = "Converted with Mammoth semantic HTML, then printed with Qt WebEngine."
    if messages:
        note = f"{note} Mammoth messages: {messages}"
    return {"note": note, "artifacts": artifacts, "pages": pages}


def _markdown_to_html(markdown_text: str, title: str) -> str:
    try:
        import marko

        body = marko.convert(markdown_text)
    except Exception:
        body = f"<pre class=\"extracted\">{html.escape(markdown_text)}</pre>"
    return _html_document(title, body)


def _render_docling_html_qt(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    from docling.document_converter import DocumentConverter

    converter = DocumentConverter()
    result = converter.convert(str(input_docx.resolve()))
    document = result.document
    if hasattr(document, "export_to_html"):
        html_text = document.export_to_html()
        html_text = _inject_css_if_full_html(html_text)
    else:
        markdown = document.export_to_markdown()
        (output_dir / "docling.md").write_text(markdown, encoding="utf-8")
        html_text = _markdown_to_html(markdown, "Docling conversion")
    html_path = output_dir / "docling.html"
    pdf_path = output_dir / "docling_qt.pdf"
    artifacts, pages = _write_html_then_pdf(
        html_text=html_text,
        html_path=html_path,
        pdf_path=pdf_path,
        output_dir=output_dir,
        max_pages=max_pages,
    )
    markdown_path = output_dir / "docling.md"
    if markdown_path.exists():
        artifacts["markdown"] = markdown_path
    return {"note": "Converted with Docling, then printed with Qt WebEngine.", "artifacts": artifacts, "pages": pages}


def _render_markitdown_html_qt(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    from markitdown import MarkItDown

    result = MarkItDown().convert(input_docx)
    markdown = result.text_content
    markdown_path = output_dir / "markitdown.md"
    markdown_path.write_text(markdown, encoding="utf-8")
    html_text = _markdown_to_html(markdown, "MarkItDown conversion")
    html_path = output_dir / "markitdown.html"
    pdf_path = output_dir / "markitdown_qt.pdf"
    artifacts, pages = _write_html_then_pdf(
        html_text=html_text,
        html_path=html_path,
        pdf_path=pdf_path,
        output_dir=output_dir,
        max_pages=max_pages,
    )
    artifacts["markdown"] = markdown_path
    return {"note": "Converted with MarkItDown to Markdown/HTML, then printed with Qt WebEngine.", "artifacts": artifacts, "pages": pages}


def _render_python_docx_html_qt(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    from docx import Document

    document = Document(str(input_docx.resolve()))
    blocks: list[str] = []
    for paragraph in document.paragraphs:
        text = paragraph.text.strip()
        if not text:
            continue
        style = paragraph.style.name.lower() if paragraph.style else ""
        escaped = html.escape(text)
        if "heading 1" in style or "title" in style:
            blocks.append(f"<h2>{escaped}</h2>")
        elif "heading 2" in style:
            blocks.append(f"<h3>{escaped}</h3>")
        elif "list" in style:
            blocks.append(f"<p class=\"muted\">- {escaped}</p>")
        else:
            blocks.append(f"<p>{escaped}</p>")
    for table in document.tables:
        rows = []
        for row_index, row in enumerate(table.rows):
            cells = "".join(
                f"<{'th' if row_index == 0 else 'td'}>{html.escape(cell.text)}</{'th' if row_index == 0 else 'td'}>"
                for cell in row.cells
            )
            rows.append(f"<tr>{cells}</tr>")
        blocks.append(f"<table>{''.join(rows)}</table>")
    html_text = _html_document("python-docx extracted HTML", "\n".join(blocks))
    html_path = output_dir / "python_docx.html"
    pdf_path = output_dir / "python_docx_qt.pdf"
    artifacts, pages = _write_html_then_pdf(
        html_text=html_text,
        html_path=html_path,
        pdf_path=pdf_path,
        output_dir=output_dir,
        max_pages=max_pages,
    )
    return {"note": "Extracted paragraphs/tables with python-docx, then printed with Qt WebEngine.", "artifacts": artifacts, "pages": pages}


def _render_docx2python_html_qt(input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    from docx2python import docx2python

    with docx2python(str(input_docx.resolve()), html=True) as content:
        extracted_text = content.text
    html_text = _html_document(
        "docx2python extracted text",
        f"<pre class=\"extracted\">{html.escape(extracted_text)}</pre>",
    )
    html_path = output_dir / "docx2python.html"
    pdf_path = output_dir / "docx2python_qt.pdf"
    artifacts, pages = _write_html_then_pdf(
        html_text=html_text,
        html_path=html_path,
        pdf_path=pdf_path,
        output_dir=output_dir,
        max_pages=max_pages,
    )
    return {"note": "Extracted text with docx2python, then printed with Qt WebEngine.", "artifacts": artifacts, "pages": pages}


RENDERERS: dict[str, Renderer] = {
    "word_com_pdf": Renderer(
        "word_com_pdf",
        "Microsoft Word COM",
        "native-pdf",
        "Uses pywin32 to ask installed Microsoft Word to export PDF.",
        _render_word_com_pdf,
    ),
    "docx2pdf_word": Renderer(
        "docx2pdf_word",
        "docx2pdf / Word",
        "native-pdf",
        "Uses docx2pdf, which delegates to Microsoft Word on Windows.",
        _render_docx2pdf_word,
    ),
    "aspose_words_pdf": Renderer(
        "aspose_words_pdf",
        "Aspose.Words",
        "commercial-pdf",
        "Uses Aspose.Words to render DOCX to PDF.",
        _render_aspose_words_pdf,
    ),
    "spire_doc_pdf": Renderer(
        "spire_doc_pdf",
        "Spire.Doc",
        "commercial-pdf",
        "Uses Spire.Doc to render DOCX to PDF.",
        _render_spire_doc_pdf,
    ),
    "libreoffice_pdf": Renderer(
        "libreoffice_pdf",
        "LibreOffice headless",
        "external-pdf",
        "Uses soffice/libreoffice CLI when installed on PATH.",
        _render_libreoffice_pdf,
    ),
    "pypandoc_html_qt": Renderer(
        "pypandoc_html_qt",
        "Pandoc HTML + Qt",
        "html-pdf",
        "Uses pypandoc/Pandoc for DOCX to HTML, then Qt WebEngine to PDF.",
        _render_pypandoc_html_qt,
    ),
    "mammoth_html_qt": Renderer(
        "mammoth_html_qt",
        "Mammoth HTML + Qt",
        "html-pdf",
        "Uses Mammoth semantic HTML, then Qt WebEngine to PDF.",
        _render_mammoth_html_qt,
    ),
    "docling_html_qt": Renderer(
        "docling_html_qt",
        "Docling HTML + Qt",
        "html-pdf",
        "Uses Docling conversion, then Qt WebEngine to PDF.",
        _render_docling_html_qt,
    ),
    "markitdown_html_qt": Renderer(
        "markitdown_html_qt",
        "MarkItDown + Qt",
        "markdown-html-pdf",
        "Uses MarkItDown conversion, then Qt WebEngine to PDF.",
        _render_markitdown_html_qt,
    ),
    "python_docx_html_qt": Renderer(
        "python_docx_html_qt",
        "python-docx extraction + Qt",
        "extracted-html-pdf",
        "Uses python-docx paragraph/table extraction, then Qt WebEngine to PDF.",
        _render_python_docx_html_qt,
    ),
    "docx2python_html_qt": Renderer(
        "docx2python_html_qt",
        "docx2python extraction + Qt",
        "extracted-html-pdf",
        "Uses docx2python extraction, then Qt WebEngine to PDF.",
        _render_docx2python_html_qt,
    ),
}


def _set_cell_shading(cell: object, fill: str) -> None:
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    tc_pr = cell._tc.get_or_add_tcPr()
    shading = OxmlElement("w:shd")
    shading.set(qn("w:fill"), fill)
    tc_pr.append(shading)


def _build_sample_chart(path: Path) -> None:
    from PIL import Image, ImageDraw

    image = Image.new("RGB", (920, 280), "#f7fafc")
    draw = ImageDraw.Draw(image)
    draw.rectangle((0, 0, 919, 279), outline="#7f8fa3", width=3)
    draw.text((34, 24), "Embedded image and shape stress area", fill="#17324d")
    labels = ["Native", "Tables", "Lists", "Images", "Footer"]
    values = [88, 73, 64, 81, 58]
    colors = ["#2f8f5b", "#3b82b8", "#d18b2f", "#7a4fb3", "#c14f4f"]
    for index, (label, value, color) in enumerate(zip(labels, values, colors)):
        x0 = 56 + index * 166
        bar_height = int(value * 1.6)
        y0 = 230 - bar_height
        draw.rectangle((x0, y0, x0 + 86, 230), fill=color)
        draw.text((x0, 238), label, fill="#27313b")
        draw.text((x0 + 18, y0 - 22), f"{value}%", fill="#27313b")
    image.save(path)


def write_sample_docx(docx_path: Path) -> None:
    from docx import Document
    from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Inches, Pt, RGBColor

    docx_path.parent.mkdir(parents=True, exist_ok=True)
    assets_dir = docx_path.parent / "sample_assets"
    assets_dir.mkdir(exist_ok=True)
    chart_path = assets_dir / "stress_chart.png"
    _build_sample_chart(chart_path)

    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.75)
    section.right_margin = Inches(0.75)
    section.header.paragraphs[0].text = "COREX DOCX renderer stress sample"
    section.footer.paragraphs[0].text = "Footer text - page rendering and margin check"

    styles = document.styles
    styles["Normal"].font.name = "Segoe UI"
    styles["Normal"].font.size = Pt(10.5)
    styles["Title"].font.name = "Segoe UI"
    styles["Title"].font.size = Pt(24)
    styles["Title"].font.color.rgb = RGBColor(23, 50, 77)

    title = document.add_paragraph(style="Title")
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.add_run("DOCX Rendering Quality Stress Sample")
    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("Headings, lists, tables, images, headers, footers, and page breaks")
    run.italic = True
    run.font.color.rgb = RGBColor(82, 97, 111)

    document.add_heading("Executive summary", level=1)
    lead = document.add_paragraph()
    lead.add_run("Purpose: ").bold = True
    lead.add_run(
        "this synthetic document is designed to make renderer differences visible. "
        "Native Word-based renderers should preserve spacing, page furniture, table "
        "geometry, and embedded media more closely than semantic HTML extractors."
    )

    callout = document.add_table(rows=1, cols=1)
    callout.alignment = WD_TABLE_ALIGNMENT.CENTER
    callout.cell(0, 0).text = (
        "Callout block: watch for background fill, internal padding, text wrapping, "
        "and separation from nearby paragraphs."
    )
    _set_cell_shading(callout.cell(0, 0), "EAF5ED")

    document.add_heading("List handling", level=1)
    for item in [
        "Numbering should keep the marker aligned with wrapped text.",
        "Bullet indentation should not collapse into plain paragraphs.",
        "Bold and italic inline emphasis should remain visible.",
    ]:
        paragraph = document.add_paragraph(style="List Bullet")
        paragraph.add_run(item)
    for item in [
        "Load the DOCX file.",
        "Convert or render the document.",
        "Rasterize the first pages for side-by-side comparison.",
    ]:
        document.add_paragraph(item, style="List Number")

    document.add_heading("Table handling", level=1)
    table = document.add_table(rows=1, cols=4)
    table.style = "Table Grid"
    table.autofit = False
    headers = ["Area", "Expected behavior", "Common drift", "Review note"]
    for index, header in enumerate(headers):
        cell = table.rows[0].cells[index]
        cell.text = header
        cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
        _set_cell_shading(cell, "DDEAF6")
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True
    rows = [
        ("Header/footer", "Preserved on each page", "Dropped in HTML", "Check page top and bottom"),
        ("Image", "Scaled inside margins", "Missing or stretched", "Compare chart position"),
        ("Table", "Readable columns", "Equal-width squeeze", "Look for clipped labels"),
        ("Spacing", "Natural paragraph rhythm", "Dense extraction", "Compare section breaks"),
    ]
    for row_values in rows:
        cells = table.add_row().cells
        for index, value in enumerate(row_values):
            cells[index].text = value

    document.add_heading("Embedded image", level=1)
    document.add_paragraph("The chart below is generated at runtime and embedded in the DOCX.")
    document.add_picture(str(chart_path), width=Inches(6.4))

    document.add_page_break()
    document.add_heading("Second page continuity", level=1)
    for index in range(1, 7):
        paragraph = document.add_paragraph()
        paragraph.add_run(f"Continuation paragraph {index}: ").bold = True
        paragraph.add_run(
            "this text gives renderers enough flow content to show page breaks, "
            "line spacing, and footer behavior. It also makes semantic extraction "
            "differences easier to spot in the comparison report."
        )

    document.save(str(docx_path))


def _run_renderer_worker(name: str, input_docx: Path, output_dir: Path, max_pages: int) -> dict[str, object]:
    renderer = RENDERERS[name]
    output_dir.mkdir(parents=True, exist_ok=True)
    started = time.perf_counter()
    try:
        payload = renderer.func(input_docx, output_dir, max_pages)
        duration_s = time.perf_counter() - started
        return _json_safe_result(
            name=name,
            label=renderer.label,
            kind=renderer.kind,
            status="ok",
            note=str(payload.get("note", "")),
            duration_s=duration_s,
            output_dir=output_dir,
            artifacts=payload.get("artifacts", {}),
            pages=payload.get("pages", []),
        )
    except SkipRenderer as exc:
        duration_s = time.perf_counter() - started
        return _json_safe_result(
            name=name,
            label=renderer.label,
            kind=renderer.kind,
            status="skipped",
            note=str(exc),
            duration_s=duration_s,
            output_dir=output_dir,
        )
    except Exception as exc:  # noqa: BLE001
        duration_s = time.perf_counter() - started
        return _json_safe_result(
            name=name,
            label=renderer.label,
            kind=renderer.kind,
            status="failed",
            note=str(exc),
            duration_s=duration_s,
            output_dir=output_dir,
            details=traceback.format_exc(),
        )


def _parse_renderer_names(values: Iterable[str] | None) -> list[str]:
    if not values:
        return list(RENDERERS)
    requested: list[str] = []
    for value in values:
        requested.extend(part.strip() for part in value.split(",") if part.strip())
    unknown = [name for name in requested if name not in RENDERERS]
    if unknown:
        raise SystemExit(f"Unknown renderer(s): {', '.join(unknown)}")
    return requested


def _worker_main(args: argparse.Namespace) -> int:
    output_dir = Path(args.output_dir).resolve()
    result = _run_renderer_worker(args.worker, Path(args.input).resolve(), output_dir, args.max_pages)
    (output_dir / "result.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
    print(json.dumps({"name": args.worker, "status": result["status"], "note": result["note"]}))
    return 0


def _run_subprocess_renderer(
    name: str,
    input_docx: Path,
    renderer_dir: Path,
    *,
    max_pages: int,
    timeout_s: int,
) -> dict[str, object]:
    command = [
        sys.executable,
        str(Path(__file__).resolve()),
        "--worker",
        name,
        "--input",
        str(input_docx.resolve()),
        "--output-dir",
        str(renderer_dir.resolve()),
        "--max-pages",
        str(max_pages),
    ]
    try:
        completed = subprocess.run(
            command,
            cwd=ROOT,
            text=True,
            capture_output=True,
            timeout=timeout_s,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        renderer = RENDERERS[name]
        return _json_safe_result(
            name=name,
            label=renderer.label,
            kind=renderer.kind,
            status="failed",
            note=f"Timed out after {timeout_s} seconds.",
            duration_s=timeout_s,
            output_dir=renderer_dir,
            details=(exc.stdout or "") + "\n" + (exc.stderr or ""),
        )

    result_path = renderer_dir / "result.json"
    if result_path.exists():
        result = json.loads(result_path.read_text(encoding="utf-8"))
        _prefix_worker_paths(result, renderer_dir)
        result["stdout"] = completed.stdout[-4000:]
        result["stderr"] = completed.stderr[-4000:]
        return result

    renderer = RENDERERS[name]
    return _json_safe_result(
        name=name,
        label=renderer.label,
        kind=renderer.kind,
        status="failed",
        note=f"Worker exited with code {completed.returncode} before writing result.json.",
        duration_s=0.0,
        output_dir=renderer_dir,
        details=completed.stdout[-4000:] + "\n" + completed.stderr[-4000:],
    )


def _prefix_worker_paths(result: dict[str, object], renderer_dir: Path) -> None:
    prefix = renderer_dir.name

    def prefixed(value: str) -> str:
        if not value:
            return value
        normalized = value.replace("\\", "/")
        if Path(normalized).is_absolute() or normalized.startswith("../"):
            return normalized
        if normalized.startswith(f"{prefix}/"):
            return normalized
        return f"{prefix}/{normalized}"

    artifacts = result.get("artifacts", {})
    if isinstance(artifacts, dict):
        result["artifacts"] = {
            key: prefixed(str(path))
            for key, path in artifacts.items()
        }
    pages = result.get("pages", [])
    if isinstance(pages, list):
        result["pages"] = [prefixed(str(path)) for path in pages]


def _write_comparison_html(report: dict[str, object], output_dir: Path) -> Path:
    cards: list[str] = []
    for item in report["results"]:
        pages = item.get("pages", [])
        artifacts = item.get("artifacts", {})
        first_page = pages[0] if pages else ""
        image = (
            f"<a href=\"{html.escape(first_page)}\"><img src=\"{html.escape(first_page)}\" alt=\"{html.escape(item['label'])} first page\"></a>"
            if first_page
            else "<div class=\"placeholder\">No raster output</div>"
        )
        links = []
        for label, path in artifacts.items():
            links.append(f"<a href=\"{html.escape(path)}\">{html.escape(label)}</a>")
        for index, path in enumerate(pages, 1):
            links.append(f"<a href=\"{html.escape(path)}\">page {index}</a>")
        details = html.escape(item.get("details", "")[:1200])
        detail_block = f"<details><summary>Details</summary><pre>{details}</pre></details>" if details else ""
        cards.append(
            textwrap.dedent(
                f"""\
                <section class="card {html.escape(item['status'])}">
                  <div class="card-head">
                    <h2>{html.escape(item['label'])}</h2>
                    <span>{html.escape(item['status'])}</span>
                  </div>
                  <p class="kind">{html.escape(item['kind'])} - {item['duration_s']}s</p>
                  <p>{html.escape(item['note'])}</p>
                  {image}
                  <p class="links">{' | '.join(links)}</p>
                  {detail_block}
                </section>
                """
            )
        )
    document = textwrap.dedent(
        f"""\
        <!doctype html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>DOCX rendering comparison</title>
          <style>
            body {{ margin: 24px; font-family: Segoe UI, Arial, sans-serif; color: #1f2933; background: #f3f6f8; }}
            h1 {{ margin-bottom: 4px; }}
            .meta {{ color: #5b6670; margin-top: 0; }}
            .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 18px; }}
            .card {{ background: white; border: 1px solid #cfd8e3; border-radius: 8px; padding: 14px; box-shadow: 0 1px 3px rgba(15, 23, 42, 0.08); }}
            .card-head {{ display: flex; justify-content: space-between; gap: 12px; align-items: start; }}
            .card h2 {{ font-size: 18px; margin: 0; }}
            .card span {{ border-radius: 999px; padding: 2px 8px; font-size: 12px; text-transform: uppercase; }}
            .ok span {{ background: #dff5e8; color: #166534; }}
            .skipped span {{ background: #eef2f7; color: #475569; }}
            .failed span {{ background: #fee2e2; color: #991b1b; }}
            .kind {{ color: #65717c; font-size: 13px; }}
            img {{ width: 100%; border: 1px solid #d5dde6; background: white; }}
            .placeholder {{ height: 220px; border: 1px dashed #aeb8c2; display: grid; place-items: center; color: #65717c; }}
            .links {{ font-size: 13px; overflow-wrap: anywhere; }}
            pre {{ white-space: pre-wrap; background: #f6f8fa; padding: 10px; border: 1px solid #d0d7de; max-height: 260px; overflow: auto; }}
          </style>
        </head>
        <body>
          <h1>DOCX rendering comparison</h1>
          <p class="meta">Input: {html.escape(report['input_docx'])}</p>
          <p class="meta">Generated: {html.escape(report['generated_at'])}</p>
          <div class="grid">
            {''.join(cards)}
          </div>
        </body>
        </html>
        """
    )
    path = output_dir / "comparison.html"
    path.write_text(document, encoding="utf-8")
    return path


def _run_parent(args: argparse.Namespace) -> int:
    renderers = _parse_renderer_names(args.only)
    if args.selftest and not args.only:
        renderers = list(QUICK_RENDERERS)

    output_dir = Path(args.output_dir).resolve() if args.output_dir else DEFAULT_OUTPUT_ROOT / datetime.now().strftime("%Y%m%d_%H%M%S")
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.input:
        input_docx = Path(args.input).resolve()
        if not input_docx.exists():
            raise SystemExit(f"Input DOCX does not exist: {input_docx}")
    else:
        input_docx = output_dir / "sample.docx"
        write_sample_docx(input_docx)

    results = []
    for name in renderers:
        print(f"Rendering {name}...")
        renderer_dir = output_dir / name
        renderer_dir.mkdir(parents=True, exist_ok=True)
        result = _run_subprocess_renderer(
            name,
            input_docx,
            renderer_dir,
            max_pages=args.max_pages,
            timeout_s=args.timeout,
        )
        results.append(result)
        print(f"  {result['status']}: {result['note']}")

    report: dict[str, object] = {
        "schema": 1,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "input_docx": _rel(input_docx, output_dir),
        "output_dir": str(output_dir),
        "results": results,
    }
    report_path = output_dir / "report.json"
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    comparison_path = _write_comparison_html(report, output_dir)

    ok_count = sum(1 for item in results if item["status"] == "ok")
    skipped_count = sum(1 for item in results if item["status"] == "skipped")
    failed_count = sum(1 for item in results if item["status"] == "failed")
    print()
    print(f"Report: {report_path}")
    print(f"Comparison: {comparison_path}")
    print(f"Summary: {ok_count} ok, {skipped_count} skipped, {failed_count} failed")
    if args.selftest and ok_count == 0:
        return 1
    return 0 if failed_count == 0 or args.keep_going_exit_zero else 1


def _list_renderers() -> int:
    for renderer in RENDERERS.values():
        print(f"{renderer.name:<24} {renderer.kind:<18} {renderer.description}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", help="DOCX file to render. A sample DOCX is generated when omitted.")
    parser.add_argument("--output-dir", help="Directory for reports and rendered artifacts.")
    parser.add_argument("--only", action="append", help="Renderer name or comma-separated renderer names.")
    parser.add_argument("--max-pages", type=int, default=3, help="Maximum PDF pages to rasterize per renderer.")
    parser.add_argument("--timeout", type=int, default=180, help="Seconds allowed per renderer subprocess.")
    parser.add_argument("--selftest", action="store_true", help="Run a quick subset suitable for smoke testing.")
    parser.add_argument("--list", action="store_true", help="List available renderer candidates and exit.")
    parser.add_argument("--keep-going-exit-zero", action="store_true", help="Return 0 even when some renderers fail.")
    parser.add_argument("--worker", choices=sorted(RENDERERS), help=argparse.SUPPRESS)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.list:
        return _list_renderers()
    if args.worker:
        if not args.input or not args.output_dir:
            parser.error("--worker requires --input and --output-dir")
        return _worker_main(args)
    return _run_parent(args)


if __name__ == "__main__":
    raise SystemExit(main())
