from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from typing import Any

from ea_node_editor.nodes.decorators import node_type
from ea_node_editor.nodes.node_specs import (
    NodeTypeSpec,
    PortSpec,
    PropertySpec,
    ReadinessRequirementSpec,
    SettingsGroupSpec,
)

BUILTIN_NODE_ICONS: Mapping[str, str] = {
    "core.constant": "core/data_object.svg",
    "core.logger": "core/article.svg",
    "core.python_script": "core/code.svg",
    "core.if": "call_split",
    "core.stream_gate": "alt_route",
    "data.boolean_toggle": "check",
    "data.construct_path": "account_tree",
    "data.deconstruct_color": "palette",
    "data.deconstruct_path": "account_tree",
    "data.excel_cell": "grid_on",
    "data.number_slider": "linear_scale",
    "data.panel": "core/article.svg",
    "data.select": "arrow_drop_down_circle",
    "math.construct_interval": "core/data_object.svg",
    "math.bounding_interval_2d": "aspect_ratio",
    "math.deconstruct_interval": "core/data_object.svg",
    "math.deconstruct_interval_2d": "aspect_ratio",
    "math.deconstruct_tensor": "view_in_ar",
    "math.field_vector_container": "storage",
    "math.physical_quantity_container": "straighten",
    "math.unit_system_container": "square_foot",
    "io.excel_read": "integrations/table_view.svg",
    "io.excel_write": "integrations/download.svg",
    "io.file_read": "integrations/description.svg",
    "io.file_write": "integrations/save.svg",
    "io.image_import": "integrations/download.svg",
    "io.image_export": "integrations/download.svg",
    "io.path_pointer": "integrations/folder.svg",
    "io.folder_explorer": "integrations/folder.svg",
    "io.combine_file_paths": "account_tree",
    "io.construct_file_path": "account_tree",
    "io.deconstruct_file_path": "account_tree",
    "io.contents_in_directory": "integrations/folder.svg",
    "io.create_directory": "create_new_folder",
    "io.move_file": "drive_file_move",
    "io.delete_file": "delete",
    "io.temporary_file_path": "description",
    "io.email_send": "integrations/mail.svg",
    "io.process_run": "integrations/terminal.svg",
    "engineering.fe_import": "integrations/download.svg",
    "engineering.cad_import": "integrations/download.svg",
    "model.viewer": "deployed_code",
    "optimization.construct_design": "design_services",
    "optimization.construct_parameters": "tune",
    "optimization.construct_responses": "analytics",
    "optimization.parameter_pool": "list",
    "optimization.parameter_setup": "tune",
    "optimization.response_pool": "analytics",
    "tabular.input": "integrations/tabular_data.svg",
    "ssh_sftp.secret": "ssh_sftp/lock.svg",
    "ssh_sftp.host": "ssh_sftp/server.svg",
    "ssh_sftp.run_command": "ssh_sftp/terminal.svg",
    "ssh_sftp.run_script": "ssh_sftp/code.svg",
    "ssh_sftp.upload": "ssh_sftp/cloud_upload.svg",
    "ssh_sftp.download": "ssh_sftp/cloud_download.svg",
    "plot.signal": "show_chart",
    "plot.scatter": "scatter_plot",
    "plot.bar": "bar_chart",
    "plot.histogram": "align_vertical_bottom",
    "plot.heatmap": "grid_view",
    "plot.contour": "terrain",
    "plot.surface": "deployed_code",
    "plot.point_cloud": "grain",
    "plot.streamlines": "air",
    "reference.construct_plane": "3d_rotation",
    "reference.construct_point": "location_on",
    "reference.construct_vector": "arrow_forward",
    "reference.deconstruct_point": "view_in_ar",
    "reference.deconstruct_vector": "view_in_ar",
    "reference.plane_container": "3d_rotation",
    "reference.reverse_vector": "swap_horiz",
    "reference.vector_length": "straighten",
    "reference.xy_plane": "grid_4x4",
    "geometry.chain_transforms": "matrix",
    "geometry.construct_transform": "matrix",
    "geometry.cylinder": "cylinder",
    "geometry.deconstruct_transform": "matrix",
    "geometry.unchain_transforms": "matrix",
    "geometry.construct_group": "select_all",
    "fea.force": "arrow_forward",
    "fea.load_container": "inventory_2",
    "mesh.deconstruct_mesh_face": "grid_on",
    "utilities.construct_view": "visibility",
    "utilities.deconstruct_date_time": "schedule",
    "utilities.deconstruct_view": "visibility",
    "ai.create_vector_collection": "database",
    "ai.inspect_vector_collection": "database",
    "ai.large_language_model": "smart_toy",
    "ai.sqlite_vector_database": "database",
    "reporting.markdown_flowchart": "git-branch",
    "reporting.markdown_flowchart_node": "git-branch",
    "security.windows_authentication": "badge",
    "core.subnode": "subnode/account_tree.svg",
    "core.subnode_input": "subnode/input.svg",
    "core.subnode_output": "subnode/output.svg",
    "passive.planning.task_card": "task_alt",
    "passive.planning.milestone_card": "flag",
    "passive.planning.risk_card": "warning",
    "passive.planning.decision_card": "gavel",
    "passive.annotation.sticky_note": "sticky_note_2",
    "passive.annotation.callout": "campaign",
    "passive.annotation.section_header": "title",
    "passive.annotation.text": "text_fields",
    "passive.annotation.group_backdrop": "comment",
    "media.panel": "image",
    "mechanical.open_model": "mechanical/open.svg",
    "mechanical.search_tree": "mechanical/search.svg",
    "mechanical.fea_table": "mechanical/table.svg",
    "mechanical.camera_views": "mechanical/views.svg",
    "mechanical.export_image": "mechanical/image.svg",
    "mechanical.run_script": "mechanical/script.svg",
    "mechanical.apdl_snippet": "mechanical/snippet.svg",
    "mechanical.save_model": "mechanical/save.svg",
    "passive.media.mail_panel": "mail",
    "web.page_viewer": "globe",
    "excalidraw.board": "draw",
    "code.jupyter_notebook": "code",
}


def builtin_node_icon(type_id: str) -> str:
    normalized_type_id = str(type_id).strip()
    try:
        return BUILTIN_NODE_ICONS[normalized_type_id]
    except KeyError as exc:
        raise KeyError(f"missing built-in node icon for {normalized_type_id!r}") from exc


def builtin_node_type_spec(
    *,
    type_id: str,
    display_name: str,
    category_path: Any,
    ports: Sequence[PortSpec],
    properties: Sequence[PropertySpec],
    **kwargs: Any,
) -> NodeTypeSpec:
    return NodeTypeSpec(
        type_id=type_id,
        display_name=display_name,
        category_path=category_path,
        icon=builtin_node_icon(type_id),
        ports=tuple(ports),
        properties=tuple(properties),
        **kwargs,
    )


def builtin_node_type(
    *,
    type_id: str,
    display_name: str,
    ports: tuple[PortSpec, ...] | list[PortSpec],
    properties: tuple[PropertySpec, ...] | list[PropertySpec],
    category_path: Any | None = None,
    category: str = "",
    collapsible: bool = True,
    description: str = "",
    keywords: tuple[str, ...] | list[str] = (),
    runtime_behavior: str = "active",
    surface_family: str = "standard",
    surface_variant: str = "",
    render_quality: Any = None,
    settings_groups: tuple[SettingsGroupSpec, ...] | list[SettingsGroupSpec] = (),
    default_expanded_settings_group_ids: tuple[str, ...] | list[str] = (),
    readiness_requirements: tuple[ReadinessRequirementSpec, ...] | list[ReadinessRequirementSpec] = (),
    solution_reuse_scope: str = "never",
) -> Callable[[type[Any]], type[Any]]:
    return node_type(
        type_id=type_id,
        display_name=display_name,
        category_path=category_path,
        category=category,
        icon=builtin_node_icon(type_id),
        ports=ports,
        properties=properties,
        collapsible=collapsible,
        description=description,
        keywords=keywords,
        runtime_behavior=runtime_behavior,
        surface_family=surface_family,
        surface_variant=surface_variant,
        render_quality=render_quality,
        settings_groups=settings_groups,
        default_expanded_settings_group_ids=default_expanded_settings_group_ids,
        readiness_requirements=readiness_requirements,
        solution_reuse_scope=solution_reuse_scope,  # type: ignore[arg-type]
    )


__all__ = [
    "BUILTIN_NODE_ICONS",
    "builtin_node_icon",
    "builtin_node_type",
    "builtin_node_type_spec",
]
